name: calculator_app
description: A modern calculator app with production-level enhancements.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  math_expressions: ^2.4.0
  flutter_vibrate: ^1.3.0
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/ 